### PR TITLE
added filename argument to source transformer

### PR DESCRIPTION
**Pull request by helloIAmPau**
Hello @felixge,
in this PR I start passing the source filename as the second argument of the sourceTransformer callbacks.
It can be helpful for cases in which you have to decide to either parse or not the source code based on the file extension.

Moreover, I added a new makefile rule running the tests into a docker container configured ad-hoc for testing purposes (your test environment is not compatible anymore with the current LTS version of node and with OSX systems).

Hope you enjoy the changes :)

### CODE REVIEW

**Comment by felixge** [comment]
Thanks!

I'm not actively maintaining any of my NPM modules these days anymore, so I merged your PR without reviewing it carefully.

If you're interested in helping with this module going forward, I'm happy to add you on NPM/GitHub as a contributor.

**Comment by helloIAmPau** [comment]
> If you're interested in helping with this module going forward, I'm happy to add you on NPM/GitHub as a contributor.

uh, yes, thank you. I'm actively using sandboxed-module in many projects.

**Comment by felixge** [comment]
What's you NPM username?

**Comment by helloIAmPau** [comment]
Ops, sorry. boemianrapsodi

**Comment by felixge** [comment]
@helloIAmPau thx, done!

```
$ npm owner add boemianrapsodi sandboxed-module
+ boemianrapsodi (sandboxed-module)
```

**Comment by helloIAmPau** [comment]
splendid

**Pull request merged**
